### PR TITLE
Redesign website

### PR DESCRIPTION
**Pull request by Tama63**
As per https://github.com/Jake0oo0/crafatar/issues/51 this is a PR to redesign the website slightly.

Waiting on @jomo for jumbotron colour ideas.

### CODE REVIEW

**Comment by jomo** [comment]
How about `#eee` (the color used in the header)?
btw, your app crashed.

**Comment by jomo** [comment]
Hmm, `#eee` doesn't [look](https://i.imgur.com/BjSPaEw.png) that nice, does it?

I've also thought about providing previews for the examples. Or maybe just show one example, a preview and the table?

What do you guys think?

**Comment by jomo** [comment]
Actually the current color isn't that bad.

@Jake0oo0 had the idea to show one preview of the examples at a time, but you can change the preview by hovering over the example URL. Hope that makes any sense

**Comment by jomo** [comment]
There we go, what do you think?

**Comment by Tama63** [comment]
Hi @jomo ,

Sorry just woke up in the UK.  So like a popover that will appear when you hover over preview code?

**Comment by Tama63** [comment]
:+1: I like the hover feature, looks really nice :)

**Pull request merged**
